[package]
name = "inspector-repro"
version = "0.1.0"
edition = "2021"

[dependencies]
revm = { git = "https://github.com/bluealloy/revm", rev = "45581c4" }
revm-bytecode = { git = "https://github.com/bluealloy/revm", rev = "45581c4" }
revm-database = { git = "https://github.com/bluealloy/revm", rev = "45581c4" }
revm-inspector = { git = "https://github.com/bluealloy/revm", rev = "45581c4" }
revm-interpreter = { git = "https://github.com/bluealloy/revm", rev = "45581c4" }
revm-primitives = { git = "https://github.com/bluealloy/revm", rev = "45581c4" }
